 local menue0e4fc6213e8b3593495a7260c3a4c2e = {
     {"Onboard", "onboard", "/usr/share/icons/hicolor/16x16/apps/onboard.png" },
 }

 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Archive Manager", "file-roller "},
     {"Arcticfox Config", "\"/opt/Arcticfox Config/arcticfox-config\" "},
     {"Arcticfox Monitor", "\"/opt/Arcticfox Monitor/arcticfox-monitor\" "},
     {"Atom", "env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom ", "/usr/share/icons/hicolor/16x16/apps/atom.png" },
     {"Calculator", "gnome-calculator"},
     {"Character Map", "gucharmap", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"Characters", "/usr/bin/gnome-characters"},
     {"ClamTk", "clamtk ", "/usr/share/pixmaps/clamtk.png" },
     {"Clocks", "gnome-clocks"},
     {"Disks", "gnome-disks"},
     {"FSearch", "fsearch"},
     {"Files", "nautilus --new-window "},
     {"Firmware", "gnome-firmware"},
     {"Fonts", "gnome-font-viewer "},
     {"GVim", "gvim -f ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"GoForIt!", "com.github.jmoerman.go-for-it", "/usr/share/icons/hicolor/16x16/apps/com.github.jmoerman.go-for-it.svg" },
     {"HP Device Manager", "hp-toolbox", "///usr/share/hplip/data/images/128x128/hp_logo.png" },
     {"Image Viewer", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
     {"Like Task Manager", "ltm"},
     {"Maps", "gapplication launch org.gnome.Maps "},
     {"Onboard", "onboard", "/usr/share/icons/hicolor/16x16/apps/onboard.png" },
     {"Passwords and Keys", "seahorse"},
     {"QTalarm", "qtalarm", "/usr/share/icons/hicolor/16x16/apps/1349069370_Alarm_Clock.png" },
     {"Screenshot", "xfce4-screenshooter", "/usr/share/icons/hicolor/16x16/apps/org.xfce.screenshooter.png" },
     {"Simplenote", "/opt/Simplenote/simplenote ", "/usr/share/icons/hicolor/16x16/apps/simplenote.png" },
     {"Text Editor", "gedit "},
     {"To Do", "gnome-todo"},
     {"USB Image Writer", "mintstick -m iso"},
     {"USB Stick Formatter", "mintstick -m format"},
     {"Vim", "xterm -e vim ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"Visual Studio Code", "/opt/visual-studio-code/code --no-sandbox --unity-launch ", "/usr/share/icons/visual-studio-code.png" },
     {"Weather", "gapplication launch org.gnome.Weather"},
     {"Winetricks", "winetricks --gui"},
     {"balenaEtcher", "/opt/balenaEtcher/balena-etcher-electron ", "/usr/share/icons/hicolor/16x16/apps/balena-etcher-electron.png" },
     {"nitrogen", "nitrogen", "/usr/share/icons/hicolor/16x16/apps/nitrogen.png" },
     {"picom", "picom"},
 }

 local menu78059f1898ed518c6ccd6a6392fa82c1 = {
     {"AUR", "xdg-open https://aur.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Bugs", "xdg-open https://bugs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Developers", "xdg-open http://www.archlinux.org/developers/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Documentation", "xdg-open https://wiki.archlinux.org/index.php/Official_Arch_Linux_Install_Guide", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Donate", "xdg-open http://www.archlinux.org/donate/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Forum", "xdg-open https://bbs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Homepage", "xdg-open http://www.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"SVN", "xdg-open http://projects.archlinux.org/svntogit/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Schwag", "xdg-open http://www.zazzle.com/archlinux/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Wiki", "xdg-open https://wiki.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"BibleTime ", "bibletime"},
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Xdotool Gui", "/usr/bin/xdotool-gui", "///usr/share/xdotool-gui/xdotoolgui.gif" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Agave", "agave", "/usr/share/icons/hicolor/16x16/apps/agave.png" },
     {"Boxy SVG", "env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/boxy-svg_boxy-svg.desktop /var/lib/snapd/snap/bin/boxy-svg ", "///var/lib/snapd/snap/boxy-svg/51/meta/gui/icon.png" },
     {"Color Picker", "gcolor3"},
     {"Darktable", "/usr/bin/darktable ", "/usr/share/icons/hicolor/16x16/apps/darktable.png" },
     {"Document Scanner", "simple-scan"},
     {"Document Viewer", "evince "},
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/org.fontforge.FontForge.png" },
     {"GNU Image Manipulation Program", "gimp-2.10 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"ImCompressor", "imcompressor "},
     {"Image Viewer", "eog "},
     {"Image Viewer", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/org.inkscape.Inkscape.png" },
     {"KolourPaint", "kolourpaint ", "/usr/share/icons/hicolor/16x16/apps/kolourpaint.png" },
     {"Krita", "krita ", "/usr/share/icons/hicolor/16x16/apps/krita.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"MyPaint", "mypaint "},
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Pencil", "\"/usr/bin/pencil\"", "/usr/share/icons/hicolor/16x16/apps/pencil.png" },
     {"PhotoFlare", "photoflare ", "/usr/share/icons/hicolor/16x16/apps/photoflare.png" },
     {"Pinta", "pinta ", "/usr/share/icons/hicolor/16x16/apps/pinta.png" },
     {"QtQR", "qtqr "},
     {"RawTherapee", "rawtherapee ", "/usr/share/icons/hicolor/16x16/apps/rawtherapee.png" },
     {"Shotwell", "shotwell ", "/usr/share/icons/hicolor/16x16/apps/shotwell.png" },
     {"Ultimaker Cura", "/usr/bin/cura ", "/usr/share/icons/hicolor/128x128/apps/cura-icon.png" },
     {"XDvi", "xdvi "},
     {"XSane - Scanning", "xsane", "/usr/share/pixmaps/xsane.xpm" },
     {"digiKam", "digikam -qwindowtitle digiKam", "/usr/share/icons/hicolor/16x16/apps/digikam.png" },
     {"drawio", "/opt/drawio/drawio ", "/usr/share/icons/hicolor/16x16/apps/drawio.png" },
     {"gThumb", "gthumb ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.gThumb.png" },
     {"showFoto", "showfoto -qwindowtitle showFoto ", "/usr/share/icons/hicolor/16x16/apps/showfoto.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Brave", "brave ", "/usr/share/icons/hicolor/16x16/apps/brave-desktop.png" },
     {"Discord", "/usr/bin/discord", "/usr/share/pixmaps/discord.png" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"FreeTube", "/opt/FreeTube/freetube "},
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"Insync", "insync start"},
     {"KDE Connect", "kdeconnect-app"},
     {"KDE Connect Indicator", "kdeconnect-indicator"},
     {"KDE Connect SMS", "kdeconnect-sms"},
     {"LanXchange", "lxcr", "/usr/share/pixmaps/lanxchange.png" },
     {"Open on connected device via KDE Connect", "kdeconnect-handler --open "},
     {"Slack", "/usr/bin/slack -s ", "/usr/share/pixmaps/slack.png" },
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"TeamViewer", "/opt/teamviewer/tv_bin/script/teamviewer", "/usr/share/icons/hicolor/16x16/apps/TeamViewer.png" },
     {"Telegram Desktop", "telegram-desktop -- ", "/usr/share/icons/hicolor/16x16/apps/telegram.png" },
     {"Tor Browser (en-US)", "/usr/bin/tor-browser ", "/usr/share/icons/hicolor/128x128/apps/tor-browser.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/pixmaps/transmission.png" },
     {"Trello", "trello --force-device-scale-factor=1.0 --disable-gpu-driver-bug-workarounds --use-gl=desktop --enable-accelerated-video-decode --enable-gpu-rasterization --enable-zero-copy --enable-features=VaapiVideoDecoder --disable-features=UseOzonePlatform", "/usr/share/pixmaps/trello.png" },
     {"VMware Horizon Client", "vmware-view ", "/usr/share/icons/hicolor/16x16/apps/vmware-horizon.png" },
     {"Viber", "viber ", "/usr/share/icons/hicolor/16x16/apps/viber.png" },
     {"What IP", "/usr/bin/whatip "},
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zoom", "/usr/bin/zoom ", "/usr/share/pixmaps/Zoom.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calendar", "gnome-calendar "},
     {"Contacts", "gnome-contacts"},
     {"Dictionary", "gnome-dictionary"},
     {"Document Viewer", "evince "},
     {"Evolution", "evolution "},
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Master PDF Editor", "/opt/master-pdf-editor-4/masterpdfeditor4 ", "///opt/master-pdf-editor-4/masterpdfeditor4.png" },
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"PDFsam", "pdfsam", "/usr/share/icons/hicolor/16x16/apps/pdfsam.png" },
     {"ReText", "/usr/bin/retext ", "/usr/share/icons/hicolor/16x16/apps/retext.png" },
     {"RedNotebook", "rednotebook", "/usr/share/icons/hicolor/16x16/apps/rednotebook.png" },
     {"Standard Notes", "standardnotes-desktop", "/usr/share/icons/standard-notes.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Android Studio", "android-studio ", "/usr/share/pixmaps/android-studio.png" },
     {"Arduino IDE", "arduino ", "/usr/share/icons/hicolor/16x16/apps/arduino.png" },
     {"Atom", "env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom ", "/usr/share/icons/hicolor/16x16/apps/atom.png" },
     {"BlueGriffon", "bluegriffon", "/usr/share/icons/hicolor/16x16/apps/bluegriffon.png" },
     {"Bluefish Editor", "bluefish ", "/usr/share/icons/hicolor/16x16/apps/bluefish.png" },
     {"Boxes", "gnome-boxes "},
     {"Brackets", "env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/brackets_brackets.desktop /var/lib/snapd/snap/bin/brackets ", "///var/lib/snapd/snap/brackets/138/usr/share/icons/hicolor/scalable/apps/brackets.svg" },
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
     {"Electron", "electron7 ", "/usr/share/pixmaps/electron7.png" },
     {"Electron", "electron6 ", "/usr/share/pixmaps/electron6.png" },
     {"Electron 11", "electron11 ", "/usr/share/pixmaps/electron11.png" },
     {"Electron 13", "electron13 ", "/usr/share/pixmaps/electron13.png" },
     {"Electron 4", "electron4 ", "/usr/share/pixmaps/electron4.png" },
     {"Electron 9", "electron9 ", "/usr/share/pixmaps/electron9.png" },
     {"Geany", "geany ", "/usr/share/icons/hicolor/16x16/apps/geany.png" },
     {"Gendarme", "/usr/bin/gendarme-wizard", "/usr/share/pixmaps/gendarme.svg" },
     {"GitHub Desktop", "/usr/bin/github-desktop ", "/usr/share/icons/hicolor/32x32/apps/github-desktop.png" },
     {"IntelliJ IDEA Community Edition", "/usr/bin/idea ", "/usr/share/pixmaps/idea.png" },
     {"IntelliJ IDEA Community Edition", "\"/usr/share/idea/bin/idea.sh\" ", "///usr/share/idea/bin/idea.svg" },
     {"Meld", "meld ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.meld.png" },
     {"Mono Documentation", "/usr/bin/monodoc", "/usr/share/icons/hicolor/16x16/apps/monodoc.png" },
     {"MonoDevelop", "monodevelop ", "/usr/share/icons/hicolor/16x16/apps/monodevelop.png" },
     {"MySQL Workbench", "sh -c 'GTK_THEME=Adwaita mysql-workbench '", "/usr/share/icons/hicolor/16x16/apps/mysql-workbench.png" },
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer ", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist ", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDBusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"Sublime Text", "subl ", "/usr/share/icons/hicolor/16x16/apps/sublime-text.png" },
     {"Violet UML Editor", "/usr/share/violetumleditor/violetumleditor.sh", "/usr/share/icons/hicolor/72x72/apps/violetumleditor.png" },
     {"Visual Studio Code", "/opt/visual-studio-code/code --no-sandbox --unity-launch ", "/usr/share/icons/visual-studio-code.png" },
     {"gsharp", "/usr/bin/gsharp"},
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Audacity", "env UBUNTU_MENUPROXY=0 audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Brasero", "brasero ", "/usr/share/icons/hicolor/16x16/apps/brasero.png" },
     {"Celluloid", "celluloid "},
     {"Cheese", "cheese"},
     {"Clapper", "com.github.rafostar.Clapper "},
     {"EasyTAG", "easytag ", "/usr/share/icons/hicolor/16x16/apps/easytag.png" },
     {"Gydl", "gydl.py"},
     {"HandBrake", "ghb "},
     {"LBRY", "/opt/LBRY/lbry ", "/usr/share/icons/hicolor/32x32/apps/lbry.png" },
     {"Music", "gnome-music"},
     {"OBS Studio", "obs", "/usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png" },
     {"Olive", "olive-editor ", "/usr/share/icons/hicolor/16x16/apps/org.olivevideoeditor.Olive.png" },
     {"PulseAudio Equalizer", "pulseaudio-equalizer-gtk", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"QWinFF", "qwinff ", "/usr/share/pixmaps/qwinff.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qt V4L2 video capture utility", "qvidcap", "/usr/share/icons/hicolor/16x16/apps/qvidcap.png" },
     {"QtAV Player", "Player -f "},
     {"QtAV QML Player", "QMLPlayer -f "},
     {"SMTube", "smtube", "/usr/share/icons/hicolor/16x16/apps/smtube.png" },
     {"Shotcut", "shotcut ", "/usr/share/icons/hicolor/64x64/apps/org.shotcut.Shotcut.png" },
     {"SimpleScreenRecorder", "simplescreenrecorder --logfile", "/usr/share/icons/hicolor/16x16/apps/simplescreenrecorder.png" },
     {"Spotify", "spotify ", "/usr/share/pixmaps/spotify-client.png" },
     {"Transmageddon Video Transcoder", "transmageddon", "/usr/share/icons/hicolor/16x16/apps/transmageddon.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Video4Linux Control Panel", "v4l2ucp", "/usr/share/icons/v4l2ucp.png" },
     {"Volume Icon", "volumeicon", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"guvcview", "guvcview", "/usr/share/icons/hicolor/128x128/apps/guvcview.png" },
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
     {"xine", "xine ", "/usr/share/icons/hicolor/16x16/apps/xine.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Alacritty", "alacritty", "/usr/share/pixmaps/Alacritty.svg" },
     {"Android File Transfer (MTP)", "android-file-transfer"},
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Boxes", "gnome-boxes "},
     {"Bulk Rename", "thunar --bulk-rename ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"Color Profile Viewer", "gcm-viewer", "/usr/share/icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Cool Retro Term", "cool-retro-term", "/usr/share/icons/hicolor/32x32/apps/cool-retro-term.png" },
     {"Disk Usage Analyzer", "baobab "},
     {"GParted", "/usr/bin/gparted ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"GSmartControl", "/usr/bin/gsmartcontrol_polkit", "/usr/share/icons/hicolor/16x16/apps/gsmartcontrol.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KSysGuard", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Konsole", "konsole", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"OpenJDK Java 11 Console", "/usr/lib/jvm/java-11-openjdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"OpenJDK Java 11 Shell", "xterm -e /usr/lib/jvm/java-11-openjdk/bin/jshell", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"OpenJDK Java 17 Console", "/usr/lib/jvm/java-17-openjdk/bin/jconsole"},
     {"OpenJDK Java 17 Shell", "xterm -e /usr/lib/jvm/java-17-openjdk/bin/jshell"},
     {"Oracle Java 17 Console", "/usr/lib/jvm/java-17-jdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java-jdk.png" },
     {"Oracle Java 17 Shell", "xterm -e /usr/lib/jvm/java-17-jdk/bin/jshell", "/usr/share/icons/hicolor/16x16/apps/java-jdk.png" },
     {"QTerminal", "qterminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"QTerminal drop down", "qterminal --drop", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Software", "gnome-software "},
     {"Startup Disk Creator", "usb-creator-kde"},
     {"System Monitor", "gnome-system-monitor"},
     {"SystemdGenie", "systemdgenie", "/usr/share/icons/gnome/16x16/categories/preferences-desktop.png" },
     {"Thunar File Manager", "thunar ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"USB Flasher", "popsicle-gtk ", "/usr/share/icons/hicolor/16x16/apps/com.system76.Popsicle.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Usage", "gnome-usage"},
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/ca.desrt.dconf-editor.png" },
     {"fish", "xterm -e fish", "/usr/share/pixmaps/fish.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessibility", menue0e4fc6213e8b3593495a7260c3a4c2e},
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Archlinux", menu78059f1898ed518c6ccd6a6392fa82c1},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

